<a href="https://colab.research.google.com/github/Harish-lvrk/PyTorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [ ]:
# using empty
a = torch.empty(2,3)

In [ ]:
a = torch.empty(4,5)

In [ ]:
a

tensor([[6.3447e+31, 3.3509e+03, 4.1052e+24],
        [3.1551e+15, 1.8123e+34, 5.1784e+22]])

while crating troch.empty() it will not create any valuesin it , it provides memory for it
what evver values in it just printing

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.7359, 0.3281, 0.9661],
        [0.5866, 0.5670, 0.1571]])

In [ ]:
# use of seed
torch.rand(2,3)

tensor([[0.8751, 0.5203, 0.4190],
        [0.5803, 0.5103, 0.6994]])

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3) # every value is between o to 1

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]]) # coustomized tensors

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2)) # 0 to 10 linear spaced with stpe

# using linspace
print("using linspace ->", torch.linspace(0,10,10)) # ten eveny spaced elements

# using eye
print("using eye ->", torch.eye(5)) # identity matrix

# using full
print("using full ->", torch.full((3, 3), 5)) #

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

Like is we want something shape like  other

In [ ]:
torch.empty_like(x) # if want to create the shapes like the other tensors

tensor([[              0,       679362608,       679366576],
        [140189685280560,               0,               0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32) # this need to specifiy

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# addition
x + 2


tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [ ]:
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

ertainly! The selected cell uses the torch.clamp() function from the PyTorch library.

torch.clamp(d, min=2, max=3): This function "clamps" the values in the tensor d so that they are within a specified range. Any value in d that is less than min will be replaced by min, and any value greater than max will be replaced by max. Values within the range [min, max] remain unchanged. In this specific code, it will ensure that all values in d are between 2 and 3 (inclusive).

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [ ]:
# sum
torch.sum(e)


tensor(28.)

In [ ]:
# sum along columns
torch.sum(e, dim=0)


tensor([14., 11.,  3.])

In [ ]:
# sum along rows
torch.sum(e, dim=1)

tensor([15., 13.])

In [ ]:
# mean
torch.mean(e)


tensor(4.6667)

In [ ]:
# mean along col
torch.mean(e, dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [ ]:
# median
torch.median(e)

tensor(4.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [ ]:
# variance
torch.var(e)

tensor(9.8667)

In [ ]:
# argmax
torch.argmax(e) # postion of the maximum

tensor(3)

In [ ]:
# argmin
torch.argmin(e)

tensor(5)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[116, 153],
        [166, 225]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [ ]:
# determinant
torch.det(h)

tensor(-315.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 0, 4],
        [3, 8, 8]])
tensor([[3, 3, 5],
        [0, 6, 4]])


In [ ]:
# greater than
i > j


tensor([[ True, False, False],
        [ True,  True,  True]])

In [ ]:
# less than
i < j


tensor([[False,  True,  True],
        [False, False, False]])

In [ ]:
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 8., 4.],
        [7., 2., 3.]])

In [ ]:
# log
torch.log(k)

tensor([[  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986]])

In [ ]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01]])

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"# sqrt
torch.sqrt(k)

tensor([[0.0000, 2.8284, 2.0000],
        [2.6458, 1.4142, 1.7321]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.1105e-04, 9.9753e-01, 7.3106e-01],
        [9.9909e-01, 2.4726e-03, 2.6894e-01]])

In [ ]:
# relu
torch.relu(k)

tensor([[0., 8., 4.],
        [7., 2., 3.]])

## Inplace Operations

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])
tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])


In [ ]:
m.add_(n) # inplace changes

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [ ]:
m

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [ ]:
n

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [ ]:
torch.relu(m)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [ ]:
m

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [ ]:
m.relu_()

tensor([[1.3486, 0.7721, 3.7028],
        [2.6275, 0.5080, 2.2696]])

In [ ]:
m

tensor([[1.3486, 0.7721, 3.7028],
        [2.6275, 0.5080, 2.2696]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [ ]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [ ]:
id(a)

140189685280800

In [ ]:
id(b)

140189685280800

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [ ]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.0340,  0.9157],
        [ 0.3079,  0.6269,  0.8277]])

In [ ]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [ ]:
id(a)

140189685280800

In [ ]:
id(b)

140189685663136

# Working with the GPUs

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
torch.rand(2,3 , device=device) # this is build over the gpu

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
torch.rand(2,3) # this is build over the cpu

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

If something is build over the cput if we want to move over the gpu we have to just use the to

In [ ]:
a = torch.rand(2,3)


In [ ]:
a

tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [ ]:
a.to(device)

tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]], device='cuda:0')

In [ ]:
a

tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

What is the diff in the speed in cpu and gpu taking the size of 100

In [ ]:
device = 'cuda'

CUDA (Compute Unified Device Architecture) is a parallel computing platform and application programming interface (API) model created by Nvidia. It allows software developers and software engineers to use a CUDA-enabled graphics processing unit (GPU) for general purpose processing – an approach called GPGPU (General-Purpose computing on Graphics Processing Units).

In the context of the code, cuda refers to the GPU device that PyTorch can use to perform computations. When torch.cuda.is_available() is True, it means that a CUDA-enabled GPU is present and can be used to accelerate computations.
Think of the GPU as a powerful engine built for parallel processing (doing many simple tasks at once). However, without the right instructions, this engine doesn't know what to do.

CUDA is the key that unlocks that power. It's:

A programming interface (API): It provides functions and tools that software developers use to write programs that can run on the GPU. Without CUDA, it would be very difficult for programmers to tell the GPU what calculations to perform.
A platform: It includes drivers, libraries, and other software that allow your computer's operating system and programs like PyTorch to communicate with and utilize the GPU's resources effectively.
So, in short, CUDA is the bridge between your software (like your PyTorch code) and the GPU's hardware. It allows you to send computationally intensive tasks to the GPU and get the results back, making things much faster for operations that can be done in parallel, like matrix multiplication in deep learning.



In [ ]:
import time

# Create tensors on CPU and GPU
size = 10000
a_cpu = torch.rand(size, size)
b_cpu = torch.rand(size, size)

a_gpu = torch.rand(size, size, device=device)
b_gpu = torch.rand(size, size, device=device)

# Measure time on CPU
start_time_cpu = time.time()
result_cpu = torch.matmul(a_cpu, b_cpu)
end_time_cpu = time.time()
cpu_time = end_time_cpu - start_time_cpu

print(f"Time taken on CPU: {cpu_time:.6f} seconds")

# Measure time on GPU
start_time_gpu = time.time()
result_gpu = torch.matmul(a_gpu, b_gpu)
# Wait for GPU operations to complete
torch.cuda.synchronize()
end_time_gpu = time.time()
gpu_time = end_time_gpu - start_time_gpu

print(f"Time taken on GPU: {gpu_time:.6f} seconds")

Time taken on CPU: 24.862242 seconds
Time taken on GPU: 0.669955 seconds


In [ ]:
import time
size = 1000


# Reshaping Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.2763, 0.0266, 0.4343],
        [0.3342, 0.4034, 0.5468]])

In [ ]:
a.reshape(3,2)

tensor([[0.2763, 0.0266],
        [0.4343, 0.3342],
        [0.4034, 0.5468]])

In [ ]:
a.flatten()

tensor([0.2763, 0.0266, 0.4343, 0.3342, 0.4034, 0.5468])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.3758, 0.5833, 0.0448, 0.1039],
         [0.7284, 0.0235, 0.0683, 0.8882],
         [0.9408, 0.9314, 0.8212, 0.5911]],

        [[0.2724, 0.1219, 0.4207, 0.5489],
         [0.1725, 0.2705, 0.6491, 0.5876],
         [0.6146, 0.6748, 0.1297, 0.6006]]])

In [ ]:
# permute
b.permute(2,0,1) # changing the positions of the dimensions

tensor([[[0.3758, 0.7284, 0.9408],
         [0.2724, 0.1725, 0.6146]],

        [[0.5833, 0.0235, 0.9314],
         [0.1219, 0.2705, 0.6748]],

        [[0.0448, 0.0683, 0.8212],
         [0.4207, 0.6491, 0.1297]],

        [[0.1039, 0.8882, 0.5911],
         [0.5489, 0.5876, 0.6006]]])

In [ ]:
import torch

# Create a simple tensor
a = torch.arange(12).reshape(2, 6)
print("Original tensor 'a':")
print(a)
print("Original shape of 'a':", a.shape)

Original tensor 'a':
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
Original shape of 'a': torch.Size([2, 6])


Let's start with a simple 2x6 tensor. The elements are arranged row by row in memory.

In [ ]:
# Using reshape to change the shape
a_reshaped = a.reshape(3, 4)
print("\nTensor after reshape(3, 4):")
print(a_reshaped)
print("Shape after reshape:", a_reshaped.shape)
print("Is reshaped tensor a view of the original?", a_reshaped._is_view())


Tensor after reshape(3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Shape after reshape: torch.Size([3, 4])
Is reshaped tensor a view of the original? True


Here, we reshape the 2x6 tensor into a 3x4 tensor. Since the total number of elements (12) is the same, and the original data was contiguous in a way that allows this new shape, `reshape` creates a view. The data is still in the same order in memory, but it's interpreted as 3 rows and 4 columns.

In [ ]:
# Using permute to change the dimension order
b = torch.arange(12).reshape(2, 2, 3)
print("\nOriginal tensor 'b':")
print(b)
print("Original shape of 'b':", b.shape)

b_permuted = b.permute(2, 0, 1)
print("\nTensor after permute(2, 0, 1):")
print(b_permuted)
print("Shape after permute:", b_permuted.shape)
print("Is permuted tensor a view of the original?", b_permuted._is_view())


Original tensor 'b':
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
Original shape of 'b': torch.Size([2, 2, 3])

Tensor after permute(2, 0, 1):
tensor([[[ 0,  3],
         [ 6,  9]],

        [[ 1,  4],
         [ 7, 10]],

        [[ 2,  5],
         [ 8, 11]]])
Shape after permute: torch.Size([3, 2, 2])
Is permuted tensor a view of the original? True


Now, let's use a 3D tensor `b` with shape (2, 2, 3). When we `permute(2, 0, 1)`, we are changing the order of the dimensions. The original dimension at index 2 (size 3) becomes the new dimension at index 0. The original dimension at index 0 (size 2) becomes the new dimension at index 1. The original dimension at index 1 (size 2) becomes the new dimension at index 2. `permute` always returns a view.

In [ ]:
# Demonstrating how modifying a view affects the original tensor
print("\nOriginal tensor 'a' before modification:")
print(a)
a_reshaped[0, 0] = 99
print("\nOriginal tensor 'a' after modifying reshaped view:")
print(a)

print("\nOriginal tensor 'b' before modification:")
print(b)
b_permuted[0, 0, 0] = 88
print("\nOriginal tensor 'b' after modifying permuted view:")
print(b)


Original tensor 'a' before modification:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

Original tensor 'a' after modifying reshaped view:
tensor([[99,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

Original tensor 'b' before modification:
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

Original tensor 'b' after modifying permuted view:
tensor([[[88,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


This example shows that both `reshape` (when it returns a view) and `permute` return views, meaning changes to the new tensor are reflected in the original tensor because they share the same underlying data.

In [ ]:
# Demonstrating reshape creating a copy when data is not contiguous
# Let's permute 'a' first, which can make it non-contiguous in certain dimensions
a_transposed = a.transpose(0, 1) # Transpose is a type of permute
print("\nTensor 'a' after transpose (a type of permute):")
print(a_transposed)
print("Is transposed tensor contiguous?", a_transposed.is_contiguous())

# Now try to reshape the transposed tensor
# This reshape will likely create a copy because the transposed data is not contiguous in the required order
a_transposed_reshaped = a_transposed.reshape(3, 4)
print("\nTensor after reshaping transposed tensor:")
print(a_transposed_reshaped)
print("Is reshaped transposed tensor a view?", a_transposed_reshaped._is_view())


Tensor 'a' after transpose (a type of permute):
tensor([[99,  6],
        [ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11]])
Is transposed tensor contiguous? False

Tensor after reshaping transposed tensor:
tensor([[99,  6,  1,  7],
        [ 2,  8,  3,  9],
        [ 4, 10,  5, 11]])
Is reshaped transposed tensor a view? False


Finally, this example shows a case where `reshape` might create a copy. After transposing tensor `a`, the data in memory is no longer in a simple row-by-row order. When we then try to `reshape` it into 3x4, PyTorch needs to create a new contiguous block of memory and copy the data into it to form the new shape. This is why `_is_view()` returns `False`.

we can alsod do the reshape right with d.resahpe(4,2,3) what is diff
That's a great question! While both reshape() and permute() can change the "look" of your tensor, they do so in fundamentally different ways, which is important for performance and how your data is accessed.

Here's the key difference:

reshape(): This method changes the shape of the tensor while keeping the underlying data contiguous in memory (if possible). It's like taking a block of building bricks and rearranging them into a new shape without changing the order of the bricks in the original pile. If the new shape is compatible with the original data's memory layout, reshape returns a view of the original tensor, meaning no new memory is allocated. If it's not compatible, it will create a copy.
permute(): This method changes the order of the dimensions of the tensor. It doesn't change the total number of elements or their order in the underlying memory. Instead, it changes how PyTorch interprets the dimensions. Think of it like changing the labels on the sides of a box without actually moving the contents inside. permute always returns a view of the original tensor.
In your example:

b.permute(2, 0, 1) changes the order of the dimensions from (2, 3, 4) to (4, 2, 3). The data in memory stays the same, but when you access b_permuted[i][j][k], PyTorch calculates which element in the original memory block that corresponds to based on the new dimension order.
b.reshape(4, 2, 3) also changes the shape to (4, 2, 3). If the original data in b was stored contiguously in a way that fits this new shape, reshape would likely return a view. However, if the data in b is not contiguous in that specific way (which can happen after operations like permute), reshape might need to create a copy of the data in a new contiguous block of memory to achieve the desired shape.
Why does this matter?

Performance: Operations on contiguous tensors are generally faster because the data is laid out sequentially in memory, which is efficient for the computer's cache. permute doesn't guarantee contiguity in the new dimension order, so subsequent operations on a permuted tensor might be slower if they require contiguous data. reshape can sometimes be slower if it needs to create a copy to make the data contiguous.
Views vs. Copies: permute always returns a view. reshape returns a view if possible, but a copy if necessary. If you modify a view, you modify the original tensor. If you modify a copy, you don't.
In summary, use permute when you just want to change the order of existing dimensions without changing the underlying memory layout. Use reshape when you want to change the shape of the tensor, and PyTorch will figure out the best way to do it, potentially making a copy to ensure contiguity if needed.

In [ ]:
b

tensor([[[0.3758, 0.5833, 0.0448, 0.1039],
         [0.7284, 0.0235, 0.0683, 0.8882],
         [0.9408, 0.9314, 0.8212, 0.5911]],

        [[0.2724, 0.1219, 0.4207, 0.5489],
         [0.1725, 0.2705, 0.6491, 0.5876],
         [0.6146, 0.6748, 0.1297, 0.6006]]])

In [ ]:
# Create a 1D tensor
a = torch.tensor([1, 2, 3, 4])
print("Original tensor 'a':")
print(a)
print("Original shape of 'a':", a.shape)

# Unsqueeze at dimension 0
a_unsqueeze_0 = a.unsqueeze(0)
print("\nTensor after unsqueeze(0):")
print(a_unsqueeze_0)
print("Shape after unsqueeze(0):", a_unsqueeze_0.shape)

# Unsqueeze at dimension 1
a_unsqueeze_1 = a.unsqueeze(1)
print("\nTensor after unsqueeze(1):")
print(a_unsqueeze_1)
print("Shape after unsqueeze(1):", a_unsqueeze_1.shape)

Original tensor 'a':
tensor([1, 2, 3, 4])
Original shape of 'a': torch.Size([4])

Tensor after unsqueeze(0):
tensor([[1, 2, 3, 4]])
Shape after unsqueeze(0): torch.Size([1, 4])

Tensor after unsqueeze(1):
tensor([[1],
        [2],
        [3],
        [4]])
Shape after unsqueeze(1): torch.Size([4, 1])


The `unsqueeze()` method adds a new dimension of size 1 to a tensor at the specified `dim` (dimension).

In the example:
- We start with a 1D tensor `a` with shape `(4,)`.
- `a.unsqueeze(0)` adds a new dimension at the beginning (index 0), resulting in a tensor with shape `(1, 4)`. This is often used to add a batch dimension.
- `a.unsqueeze(1)` adds a new dimension at index 1, resulting in a tensor with shape `(4, 1)`. This can be useful for operations that expect a column vector.

The new dimension of size 1 doesn't change the number of elements in the tensor, only how its shape is represented. `unsqueeze` always returns a view of the original tensor.

Okay, let's look at unsqueeze(). This operation is used to add a dimension of size 1 to a tensor at a specific position. This is particularly useful when you need to match the dimensions of tensors for certain operations or when preparing data for models that expect a specific number of dimensions (like a batch dimension).

Great! Now you have an example and explanation for unsqueeze().

Would you like to explore more tensor operations, such as:

Squeezing tensors: The opposite of unsqueezing, to remove dimensions of size 1.
Slicing and indexing: Accessing parts of a tensor.
Broadcasting: How operations work with tensors of different shapes.
Tensor concatenation and stacking: Combining tensors.

That's a good question! unsqueeze() is useful in several situations, primarily when you need to match the dimensions of tensors for operations or when dealing with models that expect a specific input shape. Here are a few common scenarios:

Adding a Batch Dimension: Many deep learning models expect input tensors to have a batch dimension at the beginning. If you have a single image or a single sequence of data, it might have a shape like (channels, height, width) or (sequence_length, features). You would use unsqueeze(0) to add a batch dimension, making the shape (1, channels, height, width) or (1, sequence_length, features).
Broadcasting: unsqueeze() can be used to make tensors compatible for broadcasting operations. Broadcasting allows PyTorch to perform operations on tensors with different shapes by "stretching" the smaller tensor to match the larger one. Adding a dimension of size 1 with unsqueeze() can help align the dimensions so broadcasting can occur correctly.
Matrix Multiplication and Linear Algebra: Sometimes, linear algebra operations require specific tensor shapes (e.g., a column vector vs. a row vector). unsqueeze() can be used to add a dimension to create the required shape for these operations. For example, if you have a 1D tensor a of shape (n,) and you want to perform a matrix multiplication with a matrix M of shape (m, n), you might need to unsqueeze(1) a to make it a column vector of shape (n, 1) so that M @ a.unsqueeze(1) is a valid operation.
Working with Convolutional Layers: Convolutional layers in neural networks typically expect input in a specific format, often with a channel dimension. If your data doesn't have this dimension (e.g., a grayscale image), you might need to unsqueeze() to add a channel dimension of size 1.
In essence, you use unsqueeze() whenever you have a tensor and you need to add a dimension of size 1 to its shape at a particular position to satisfy the requirements of an operation, a function, or a model.

In [ ]:
import numpy as np

# Create a NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])
print("NumPy array:", numpy_array)
print("Type of NumPy array:", type(numpy_array))

# Convert NumPy array to PyTorch tensor
torch_tensor = torch.from_numpy(numpy_array)
print("\nPyTorch tensor:", torch_tensor)
print("Type of PyTorch tensor:", type(torch_tensor))

NumPy array: [1 2 3 4 5]
Type of NumPy array: <class 'numpy.ndarray'>

PyTorch tensor: tensor([1, 2, 3, 4, 5])
Type of PyTorch tensor: <class 'torch.Tensor'>


In [ ]:
# Create a tensor with dimensions of size 1
b = torch.zeros(1, 2, 1, 3, 1)
print("Original tensor 'b':")
print(b)
print("Original shape of 'b':", b.shape)

# Squeeze all dimensions of size 1
b_squeezed = b.squeeze()
print("\nTensor after squeeze():")
print(b_squeezed)
print("Shape after squeeze():", b_squeezed.shape)

# Squeeze a specific dimension
b_squeezed_dim1 = b.squeeze(1)
print("\nTensor after squeeze(1):")
print(b_squeezed_dim1)
print("Shape after squeeze(1):", b_squeezed_dim1.shape)

# Squeeze another specific dimension
b_squeezed_dim4 = b.squeeze(4)
print("\nTensor after squeeze(4):")
print(b_squeezed_dim4)
print("Shape after squeeze(4):", b_squeezed_dim4.shape)

Original tensor 'b':
tensor([[[[[0.],
           [0.],
           [0.]]],


         [[[0.],
           [0.],
           [0.]]]]])
Original shape of 'b': torch.Size([1, 2, 1, 3, 1])

Tensor after squeeze():
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Shape after squeeze(): torch.Size([2, 3])

Tensor after squeeze(1):
tensor([[[[[0.],
           [0.],
           [0.]]],


         [[[0.],
           [0.],
           [0.]]]]])
Shape after squeeze(1): torch.Size([1, 2, 1, 3, 1])

Tensor after squeeze(4):
tensor([[[[0., 0., 0.]],

         [[0., 0., 0.]]]])
Shape after squeeze(4): torch.Size([1, 2, 1, 3])


The `squeeze()` method removes dimensions of size 1 from a tensor.

- When called without any arguments (`b.squeeze()`), it removes all dimensions of size 1.
- When called with a specific dimension (`b.squeeze(dim)`), it removes the dimension at the specified index *only if* that dimension has a size of 1. If the dimension's size is not 1, the tensor remains unchanged.

In the example:
- We start with a tensor `b` with shape `(1, 2, 1, 3, 1)`. It has dimensions of size 1 at indices 0, 2, and 4.
- `b.squeeze()` removes all dimensions of size 1, resulting in a tensor with shape `(2, 3)`.
- `b.squeeze(1)` attempts to remove the dimension at index 1. Since this dimension has a size of 2 (not 1), it is not removed, and the shape remains `(1, 2, 1, 3, 1)`.
- `b.squeeze(4)` attempts to remove the dimension at index 4. Since this dimension has a size of 1, it is removed, resulting in a tensor with shape `(1, 2, 1, 3)`.

`squeeze()` also returns a view of the original tensor if the operation is possible without changing the data's memory layout.